# This file created by conda-build 3.0.30
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/hdf4-4.2.13-on-linux_64, last modified Thu Nov  9 15:50:25 2017
# ------------------------------------------------

package:
    name: hdf4
    version: 4.2.13
source:
    fn: hdf-4.2.13.tar.bz2
    patches:
        - max_files.patch
    sha256: 55d3a42313bda0aba7b0463687caf819a970e0ba206f5ed2c23724f80d2ae0f3
    url: http://www.hdfgroup.org/ftp/HDF/HDF_Current/src/hdf-4.2.13.tar.bz2
build:
    number: '2'
    run_exports:
        - hdf4 >=4.2.13,<4.2.14.0a0
    string: h3ca952b_2
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1  
        - bison 3.0.4 h2db1b24_1
        - flex 2.6.4 ha10e3a4_1
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3  
        - gfortran_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1  
        - gxx_linux-64 7.3.0 h553295d_3 
        - jpeg 9b h024ee3a_2
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - m4 1.4.18 h4e445db_0
        - zlib 1.2.11 ha838bed_2
    host:
        - jpeg 9b h024ee3a_2
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - zlib 1.2.11 ha838bed_2
    run:
        - jpeg >=9b,<10a
        - libgcc-ng 7.3.0.*
        - libstdcxx-ng 7.3.0.*
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - hdiff -V
        - test -f ${PREFIX}/lib/libdf.a
        - test -f ${PREFIX}/lib/libmfhdf.a
        - test -f ${PREFIX}/lib/libdf.so
        - test -f ${PREFIX}/lib/libmfhdf.so
about:
    home: http://www.hdfgroup.org/HDF4/
    license: BSD 3-Clause
    license_family: BSD
    license_file: COPYING
    summary: Library and multi-object file format for storing and managing data between
        machines.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
